In [166]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt

In [167]:
Roots,Weights =np.polynomial.laguerre.laggauss(2)
Roots

array([0.58578644, 3.41421356])

In [168]:
Weights

array([0.85355339, 0.14644661])

In [169]:
x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)

In [170]:
def GetLaguerre(n,x):
    
    if n==0:
        LN=1
    elif n==1:
        LN=(1-x)
    else:    
        LN = ((2*n-1-x)*GetLaguerre(n-1,x)-(n-1)*GetLaguerre(n-2,x))/n
    return LN

In [171]:
GetLaguerre(2,x)

(1 - x)*(3 - x)/2 - 1/2

In [172]:
a=1
b=-4
c=2
X2=(-b+np.sqrt(b**2-4*a*c))/2*a
X1=(-b-np.sqrt(b**2-4*a*c))/2*a
X1,X2


(0.5857864376269049, 3.414213562373095)

In [173]:
Roots,Weights=np.polynomial.laguerre.laggauss(20)

In [174]:
def todo (n):
    funcion = lambda x: (x-X2)/(X1-X2)
    I = 0
    for i in range(n):
        I += Weights[i]*funcion(Roots[i])
    return I

In [175]:
w1=todo(20)
w1

0.8535533905932817

In [176]:
def todo2 (n):
    funcion = lambda x: (x-X1)/(X2-X1)
    I = 0
    for i in range(n):
        I += Weights[i]*funcion(Roots[i])
    return I

In [177]:
w2=todo2(20)
w2

0.14644660940671841

Muestre que un polinomio de grado 3 es exacto

In [178]:
def integral (n):
    funcion = lambda x: x**3
    I = 0
    for i in range(n):
        I += Weights[i]*funcion(Roots[i])
    return I

In [179]:
integral(20)

5.99999999999986

Polinomio de grado 3

In [180]:
Roots,Weights =np.polynomial.laguerre.laggauss(3)

In [181]:
G=GetLaguerre(3,x)

In [182]:
sym.expand(G)

-x**3/6 + 3*x**2/2 - 3*x + 1

In [183]:
Roots

array([0.41577456, 2.29428036, 6.28994508])

In [184]:
Weights

array([0.71109301, 0.27851773, 0.01038926])

In [185]:
x1=Roots[0]
x2=Roots[1]
x3=Roots[2]

In [186]:
Roots,Weights=np.polynomial.laguerre.laggauss(20)

In [187]:
def W1 (n):
    funcion = lambda x: ((x-x2)/(x1-x2))*((x-x3)/(x1-x3))
    I = 0
    for i in range(n):
        I += Weights[i]*funcion(Roots[i])
    return I

In [188]:
w1=W1(20)

In [189]:
def W2 (n):
    funcion = lambda x: ((x-x1)/(x2-x1))*((x-x3)/(x2-x3))
    I = 0
    for i in range(n):
        I += Weights[i]*funcion(Roots[i])
    return I

In [190]:
w2=W2(20)

In [191]:
def W3 (n):
    funcion = lambda x: ((x-x2)/(x3-x2))*((x-x1)/(x3-x1))
    I = 0
    for i in range(n):
        I += Weights[i]*funcion(Roots[i])
    return I

In [192]:
w3=W3(20)

In [194]:
suma= (x1**3)*w1+(x2**3)*w2+(x3**3)*w3
suma


5.999999999999968